### ISSUE TITLE
What algorithm

### ISSUE THREAD

**Issue by mouhsineelachbi** [surya-veer/RealTime-DigitRecognition#2]
Hey
did you use SVM to make this app ?

**Comment by surya-veer** [comment]
I have created two models.
One is CNN and other is simple SVM.
I have used keras for implementing CNN and trained it on 28X28 mnist, sklearn is used for SVM and trained on 8X8 mnist dataset.

**Comment by mouhsineelachbi** [comment]
can you give me the link of SVM model please ?

**Comment by surya-veer** [comment]
Here is the link:
https://github.com/surya-veer/RealTime-DigitRecognition/blob/master/models_svc/digit_recognition.py
