### ISSUE TITLE
add image that contain some digit on paper

### ISSUE THREAD

**Issue by alghouts** [surya-veer/RealTime-DigitRecognition#4]
i had a problem, maybe you can change how to change the input from realtime handwriting on pygame to image that contain some digit please. below i attach example of image that contain some digit on paper.
![whatsapp image 2019-02-11 at 17 05 04](https://user-images.githubusercontent.com/31149514/52556477-3fc13000-2e1f-11e9-8f05-75a95d89329f.jpeg)

**Comment by surya-veer** [comment]
Thanks for the suggestion @alghouts 
I can do it but I am a little busy. I will do it when I will find some time.

You can do this by following these steps and can contribute to this repo:
>>threshold image 
>>find contours 
>>apply blur filter and do some erosion and dilation.
>> get extended contours and pass through the classifier.
